from pathlib import Path
from textwrap import wrap

from jinja2 import Environment, FileSystemLoader, select_autoescape

from app.schemas import Analysis

ROOT = Path(__file__).parent.parent
env = Environment(
    loader=FileSystemLoader(ROOT / "templates"), autoescape=select_autoescape(["html", "xml"])
)


def render_pack(analysis: Analysis, include_notes: bool = False) -> str:
    return env.get_template("evidence_pack.html.j2").render(
        analysis=analysis, include_notes=include_notes
    )


def pdf_pack(analysis: Analysis, include_notes: bool = False) -> bytes:
    # WeasyPrint depends on system Pango/GObject libraries, so keep the import
    # lazy: API health and HTML preview remain available when PDF support has
    # not yet been installed on a deployment host.
    try:
        from weasyprint import HTML

        return HTML(
            string=render_pack(analysis, include_notes), base_url=str(ROOT / "static")
        ).write_pdf()
    except (ImportError, OSError):
        return fallback_pdf_pack(analysis, include_notes)


def fallback_pdf_pack(analysis: Analysis, include_notes: bool = False) -> bytes:
    """Create a readable PDF when a host lacks WeasyPrint native libraries.

    The HTML/Jinja pack remains the primary renderer. This dependency-free
    fallback preserves the reviewer-facing claims, source excerpts, and notes
    instead of failing the download endpoint on minimal deployment hosts.
    """
    summary = analysis.result.summary
    lines = [
        "Tether Evidence Pack",
        f"{analysis.doc_type.replace('_', ' ').title()} · Trust score {summary.trust_score}/100",
        (
            f"{summary.evidence_backed} evidence-backed claims · "
            f"{summary.needing_changes} claims needing changes · "
            f"{summary.privacy_flags} privacy flags"
        ),
        "",
        "Evidence-backed claims",
    ]
    included = [claim for claim in analysis.result.claims if claim.color in {"green", "yellow"}]
    for claim in included:
        lines.extend(
            [
                "",
                f"{claim.action}: {claim.text}",
                f"Recommended wording: {claim.accepted_rewrite or claim.safe_rewrite}",
                f"Evidence match: {claim.evidence_match}",
            ]
        )
        for snippet in claim.evidence_snippets:
            page = f", page {snippet.page}" if snippet.page else ""
            lines.append(f"Source: {snippet.file_name}{page} — {snippet.text}")
        if claim.provenance_note:
            lines.append(f"Provenance: {claim.provenance_note}")
    if include_notes:
        lines.extend(["", "Improvement notes"])
        for claim in analysis.result.claims:
            if claim.color in {"red", "purple"}:
                lines.append(f"{claim.text} — {claim.safe_rewrite}")
    lines.extend(["", "Generated by Tether — evidence reviewed for claim-to-source alignment."])
    return _plain_text_pdf(lines)


def _plain_text_pdf(lines: list[str]) -> bytes:
    """Encode wrapped plain text as a compact, standards-compliant PDF."""
    wrapped = [piece for line in lines for piece in (wrap(line, width=88) or [""])]
    pages = [wrapped[index : index + 46] for index in range(0, len(wrapped), 46)] or [[]]
    objects: list[bytes] = []
    page_ids: list[int] = []
    content_ids: list[int] = []
    # Object 1 is the catalog; 2 is the pages tree; 3 is the reusable font.
    next_id = 4
    for _page in pages:
        page_ids.append(next_id)
        content_ids.append(next_id + 1)
        next_id += 2
    objects.extend([b"<< /Type /Catalog /Pages 2 0 R >>", b"", b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"])
    objects[1] = f"<< /Type /Pages /Kids [{' '.join(f'{page} 0 R' for page in page_ids)}] /Count {len(page_ids)} >>".encode()
    for page_id, content_id, page in zip(page_ids, content_ids, pages):
        stream_lines = [b"BT", b"/F1 11 Tf", b"54 756 Td", b"14 TL"]
        for index, line in enumerate(page):
            escaped = line.encode("latin-1", "replace").replace(b"\\", b"\\\\").replace(b"(", b"\\(").replace(b")", b"\\)")
            if index:
                stream_lines.append(b"T*")
            stream_lines.append(b"(" + escaped + b") Tj")
        stream_lines.append(b"ET")
        stream = b"\n".join(stream_lines)
        objects.append(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_id} 0 R >>".encode())
        objects.append(b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream")
    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, obj in enumerate(objects, 1):
        offsets.append(len(pdf))
        pdf.extend(f"{number} 0 obj\n".encode())
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")
    xref = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode())
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode())
    pdf.extend(f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode())
    return bytes(pdf)
