const claims = [
  {id:1, text:'Led a team of 12 students to build a campus composting platform.', verdict:'Evidence backed', kind:'measurable', confidence:94, color:'#10b981', evidence:'GreenLoop impact report lists twelve named student contributors and describes the platform launch.', rewrite:'Led a 12-student team that launched GreenLoop, a campus composting platform.', source:'GreenLoop_impact_report.pdf · Page 2'},
  {id:2, text:'Platform used by 500 students.', verdict:'Needs proof', kind:'unverifiable', confidence:62, color:'#f59e0b', evidence:null, rewrite:'Built a platform piloted with students across campus.', source:null},
  {id:3, text:'Diverted 40% of dining hall waste.', verdict:'Evidence backed', kind:'measurable', confidence:89, color:'#10b981', evidence:'The impact report records a 40% reduction in compostable waste sent to landfill during the spring pilot.', rewrite:'During our spring pilot, diverted 40% of tracked dining hall compostable waste.', source:'GreenLoop_impact_report.pdf · Page 4'},
  {id:4, text:'Raised $3,000 for local food security programs.', verdict:'Privacy risk', kind:'sensitive', confidence:76, color:'#a78bfa', evidence:'Fundraiser receipt confirms a $3,000 transfer, but includes a donor phone number that should not be shared.', rewrite:'Raised $3,000 for local food-security programs through a student fundraiser.', source:'fundraiser_receipt.png · Redacted copy'}
];
const claimList=document.querySelector('#claims'), inspector=document.querySelector('#inspectorContent');
function renderClaims(){claimList.innerHTML=claims.map((c,i)=>`<article class="claim ${i===0?'selected':''}" style="--color:${c.color}" data-id="${c.id}"><div class="claim-top"><p>“${c.text}”</p><span class="tag">${c.verdict}</span></div><div class="claim-meta"><span>${c.kind}</span><span>${c.confidence}% confidence</span></div><div class="bar"><i style="width:${c.confidence}%"></i></div></article>`).join('');document.querySelectorAll('.claim').forEach(el=>el.addEventListener('click',()=>selectClaim(+el.dataset.id)));}
function selectClaim(id){const c=claims.find(x=>x.id===id);document.querySelectorAll('.claim').forEach(x=>x.classList.toggle('selected',+x.dataset.id===id));inspector.innerHTML=`<p class="evidence-kicker">${c.verdict.toUpperCase()} · ${c.confidence}% CONFIDENCE</p><h3 class="inspect-claim">“${c.text}”</h3><div class="compare"><div class="compare-box"><label>ORIGINAL CLAIM</label><p>${c.text}</p></div><div class="compare-box rewrite"><label>SUGGESTED SAFE REWRITE</label><p>${c.rewrite}</p></div></div>${c.evidence?`<div class="source"><h3>Matched evidence</h3><div class="source-card"><p>“${c.evidence}”</p><small>${c.source}</small></div></div>`:`<div class="source"><h3>Missing evidence</h3><div class="source-card" style="border-color:#f59e0b;background:#78350f18"><p>No direct source supports this exact usage number. Add analytics, a school letter, or soften the claim.</p><small style="color:#fbbf24">ACTION REQUIRED</small></div></div>`}<details class="reasoning"><summary>View Nemotron reasoning trace</summary><p>Claim classified as ${c.kind}. Tether compared the specific wording against uploaded sources and applied a credibility and privacy check before assigning this verdict.</p></details>`;}
renderClaims();selectClaim(1);
const dz=document.querySelector('#dropzone'), fi=document.querySelector('#fileInput');dz.addEventListener('click',()=>fi.click());dz.addEventListener('dragover',e=>{e.preventDefault();dz.style.borderColor='#10b981'});dz.addEventListener('dragleave',()=>dz.style.borderColor='');dz.addEventListener('drop',e=>{e.preventDefault();dz.style.borderColor='';addFiles([...e.dataTransfer.files])});fi.addEventListener('change',()=>addFiles([...fi.files]));function addFiles(items){const holder=document.querySelector('#files');items.forEach(f=>{const el=document.createElement('div');el.className='file';el.innerHTML=`<b>NEW</b><span><strong>${f.name}</strong><small>Ready to inspect</small></span><button aria-label="Remove file">×</button>`;holder.append(el);el.querySelector('button').onclick=()=>el.remove()})}document.querySelectorAll('.file button').forEach(b=>b.onclick=()=>b.closest('.file').remove());
document.querySelector('#auditButton').addEventListener('click',()=>{const btn=document.querySelector('#auditButton');btn.innerHTML='◌ Analyzing evidence…';btn.disabled=true;setTimeout(()=>{btn.innerHTML='<span>✦</span> Run Nemotron Audit';btn.disabled=false;const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)},900)});document.querySelector('#exportButton').addEventListener('click',()=>window.print());
