let claims = [
  {id:1, text:'Led a team of 12 students to build a campus composting platform.', verdict:'Evidence backed', kind:'measurable', confidence:94, color:'#10b981', evidence:'GreenLoop impact report lists twelve named student contributors and describes the platform launch.', rewrite:'Led a 12-student team that launched GreenLoop, a campus composting platform.', source:'GreenLoop_impact_report.pdf · Page 2'},
  {id:2, text:'Platform used by 500 students.', verdict:'Needs proof', kind:'unverifiable', confidence:62, color:'#f59e0b', evidence:null, rewrite:'Built a platform piloted with students across campus.', source:null},
  {id:3, text:'Diverted 40% of dining hall waste.', verdict:'Evidence backed', kind:'measurable', confidence:89, color:'#10b981', evidence:'The impact report records a 40% reduction in compostable waste sent to landfill during the spring pilot.', rewrite:'During our spring pilot, diverted 40% of tracked dining hall compostable waste.', source:'GreenLoop_impact_report.pdf · Page 4'},
  {id:4, text:'Raised $3,000 for local food security programs.', verdict:'Privacy risk', kind:'sensitive', confidence:76, color:'#a78bfa', evidence:'Fundraiser receipt confirms a $3,000 transfer, but includes a donor phone number that should not be shared.', rewrite:'Raised $3,000 for local food-security programs through a student fundraiser.', source:'fundraiser_receipt.png · Redacted copy'}
];
const claimList=document.querySelector('#claims'), inspector=document.querySelector('#inspectorContent');
function renderClaims(){claimList.innerHTML=claims.map((c,i)=>`<article class="claim ${i===0?'selected':''}" style="--color:${c.color}" data-id="${c.id}"><div class="claim-top"><p>“${c.text}”</p><span class="tag">${c.verdict}</span></div><div class="claim-meta"><span>${c.kind}</span><span>${c.confidence}% confidence</span></div><div class="bar"><i style="width:${c.confidence}%"></i></div></article>`).join('');document.querySelectorAll('.claim').forEach(el=>el.addEventListener('click',()=>selectClaim(+el.dataset.id)));}
function selectClaim(id){const c=claims.find(x=>x.id===id);document.querySelectorAll('.claim').forEach(x=>x.classList.toggle('selected',+x.dataset.id===id));inspector.innerHTML=`<p class="evidence-kicker">${c.verdict.toUpperCase()} · ${c.confidence}% CONFIDENCE</p><h3 class="inspect-claim">“${c.text}”</h3><div class="compare"><div class="compare-box"><label>ORIGINAL CLAIM</label><p>${c.text}</p></div><div class="compare-box rewrite"><label>SUGGESTED SAFE REWRITE</label><p>${c.rewrite}</p></div></div>${c.source?`<div class="source"><h3>Matched evidence</h3><div class="source-card"><p>“${c.evidence}”</p><small>${c.source}</small></div></div>`:`<div class="source"><h3>Missing evidence</h3><div class="source-card" style="border-color:#f59e0b;background:#78350f18"><p>${c.evidence||'No direct source supports this exact claim. Add analytics, a school letter, or soften the claim.'}</p><small style="color:#fbbf24">ACTION REQUIRED</small></div></div>`}<details class="reasoning"><summary>View Nemotron reasoning trace</summary><p>Claim classified as ${c.kind}. Tether compared the specific wording against uploaded sources and applied a credibility and privacy check before assigning this verdict.</p></details>`;}
renderClaims();selectClaim(1);
const dz=document.querySelector('#dropzone'), fi=document.querySelector('#fileInput');dz.addEventListener('click',()=>fi.click());dz.addEventListener('dragover',e=>{e.preventDefault();dz.style.borderColor='#10b981'});dz.addEventListener('dragleave',()=>dz.style.borderColor='');dz.addEventListener('drop',e=>{e.preventDefault();dz.style.borderColor='';addFiles([...e.dataTransfer.files])});fi.addEventListener('change',()=>addFiles([...fi.files]));function addFiles(items){const holder=document.querySelector('#files');items.forEach(f=>{const el=document.createElement('div');el.className='file';el.innerHTML=`<b>NEW</b><span><strong>${f.name}</strong><small>Ready to inspect</small></span><button aria-label="Remove file">×</button>`;holder.append(el);el.querySelector('button').onclick=()=>el.remove()})}document.querySelectorAll('.file button').forEach(b=>b.onclick=()=>b.closest('.file').remove());
function labelFor(claim){return {green:'Evidence backed',yellow:'Needs proof',red:'Unsupported',purple:'Privacy risk'}[claim.color]||claim.action}
function hydrateAnalysis(analysis){const colors={green:'#10b981',yellow:'#f59e0b',red:'#fb7185',purple:'#a78bfa'};claims=analysis.result.claims.map(claim=>({id:claim.id,text:claim.text,verdict:labelFor(claim),kind:claim.category,confidence:Math.round(claim.confidence*100),color:colors[claim.color],evidence:claim.evidence_match,rewrite:claim.safe_rewrite,source:claim.evidence_snippets[0]?`${claim.evidence_snippets[0].file_name}${claim.evidence_snippets[0].page?` · Page ${claim.evidence_snippets[0].page}`:''}`:null}));document.querySelector('#score').textContent=analysis.result.summary.trust_score;document.querySelector('.score-copy p').textContent='Live Nemotron result';document.querySelector('.score-copy h3').textContent=`${analysis.result.summary.evidence_backed} claims are ready to publish.`;document.querySelector('.score-copy span').textContent=`${analysis.result.summary.needing_changes} claims need changes and ${analysis.result.summary.privacy_flags} privacy flag needs review.`;document.querySelector('.metrics').innerHTML=`<div><b>${analysis.result.summary.evidence_backed}</b><span>Verified</span></div><div><b>${analysis.result.summary.needing_changes}</b><span>Needs proof</span></div><div><b>${analysis.result.summary.privacy_flags}</b><span>Privacy flag</span></div>`;document.querySelector('.claim-title span').textContent=`${claims.length} reviewed`;renderClaims();selectClaim(claims[0].id)}
async function waitForAnalysis(id){for(let attempt=0;attempt<20;attempt++){const response=await fetch(`/api/analyses/${id}`);const analysis=await response.json();if(analysis.status==='complete')return analysis;if(analysis.status==='failed')throw new Error(analysis.error||'The audit could not finish');await new Promise(resolve=>setTimeout(resolve,500))}throw new Error('The audit is taking longer than expected')}
document.querySelector('#auditButton').addEventListener('click',async()=>{const btn=document.querySelector('#auditButton'),toast=document.querySelector('#toast');btn.innerHTML='◌ Analyzing evidence…';btn.disabled=true;try{const form=new FormData();form.append('doc_type','scholarship_essay');form.append('draft_text',document.querySelector('#draft').value);[...fi.files].slice(0,3).forEach(file=>form.append('files',file));const created=await fetch('/api/analyses',{method:'POST',body:form});if(!created.ok)throw new Error('Tether could not start the audit');hydrateAnalysis(await waitForAnalysis((await created.json()).id));toast.textContent='Live Nemotron audit complete';toast.classList.add('show')}catch(error){toast.textContent=error.message;toast.classList.add('show')}finally{btn.innerHTML='<span>✦</span> Run Nemotron Audit';btn.disabled=false;setTimeout(()=>toast.classList.remove('show'),3200)}});document.querySelector('#exportButton').addEventListener('click',()=>window.print());
