let claims = [
  {id:1, text:'Led a team of 12 students to build a campus composting platform.', verdict:'Evidence backed', kind:'measurable', confidence:94, color:'#10b981', evidence:'GreenLoop impact report lists twelve named student contributors and describes the platform launch.', rewrite:'Led a 12-student team that launched GreenLoop, a campus composting platform.', source:'GreenLoop_impact_report.pdf · Page 2'},
  {id:2, text:'Platform used by 500 students.', verdict:'Needs proof', kind:'unverifiable', confidence:62, color:'#f59e0b', evidence:null, rewrite:'Built a platform piloted with students across campus.', source:null},
  {id:3, text:'Diverted 40% of dining hall waste.', verdict:'Evidence backed', kind:'measurable', confidence:89, color:'#10b981', evidence:'The impact report records a 40% reduction in compostable waste sent to landfill during the spring pilot.', rewrite:'During our spring pilot, diverted 40% of tracked dining hall compostable waste.', source:'GreenLoop_impact_report.pdf · Page 4'},
  {id:4, text:'Raised $3,000 for local food security programs.', verdict:'Privacy risk', kind:'sensitive', confidence:76, color:'#a78bfa', evidence:'Fundraiser receipt confirms a $3,000 transfer, but includes a donor phone number that should not be shared.', rewrite:'Raised $3,000 for local food-security programs through a student fundraiser.', source:'fundraiser_receipt.png · Redacted copy'}
];
const claimList=document.querySelector('#claims'), inspector=document.querySelector('#inspectorContent');
function renderClaims(){claimList.innerHTML=claims.map((c,i)=>`<article class="claim ${i===0?'selected':''}" style="--color:${c.color}" data-id="${c.id}"><div class="claim-top"><p>“${c.text}”</p><span class="tag">${c.verdict}</span></div><div class="claim-meta"><span>${c.kind}</span><span>${c.confidence}% confidence</span></div><div class="bar"><i style="width:${c.confidence}%"></i></div></article>`).join('');document.querySelectorAll('.claim').forEach(el=>el.addEventListener('click',()=>selectClaim(+el.dataset.id)));}
function selectClaim(id){const c=claims.find(x=>x.id===id);if(!c){inspector.innerHTML='<div class="inspector-empty">No factual claims were extracted. Add a draft with specific achievements, dates, or outcomes.</div>';return}document.querySelectorAll('.claim').forEach(x=>x.classList.toggle('selected',+x.dataset.id===id));inspector.innerHTML=`<p class="evidence-kicker">${c.verdict.toUpperCase()} · ${c.confidence}% CONFIDENCE</p><h3 class="inspect-claim">“${c.text}”</h3><div class="compare"><div class="compare-box"><label>ORIGINAL CLAIM</label><p>${c.text}</p></div><div class="compare-box rewrite"><label>SUGGESTED SAFE REWRITE</label><p>${c.rewrite}</p></div></div>${c.source?`<div class="source"><h3>Matched evidence</h3><div class="source-card"><p>“${c.evidence}”</p><small>${c.source}</small></div></div>`:`<div class="source"><h3>Missing evidence</h3><div class="source-card" style="border-color:#f59e0b;background:#78350f18"><p>${c.evidence||'No direct source supports this exact claim. Add analytics, a school letter, or soften the claim.'}</p><small style="color:#fbbf24">ACTION REQUIRED</small></div></div>`}<details class="reasoning"><summary>View Nemotron reasoning trace</summary><p>Claim classified as ${c.kind}. Tether compared the specific wording against uploaded sources and applied a credibility and privacy check before assigning this verdict.</p></details>`;}
renderClaims();selectClaim(1);
const dz=document.querySelector('#dropzone'),fi=document.querySelector('#fileInput'),fileHolder=document.querySelector('#files'),counter=document.querySelector('.counter'),draft=document.querySelector('#draft'),draftLabel=document.querySelector('#draftLabel'),toast=document.querySelector('#toast');
let selectedDocType='scholarship_essay',selectedFiles=[];
const docLabels={scholarship_essay:'SCHOLARSHIP ESSAY DRAFT',resume:'RESUME DRAFT',project_proposal:'PROJECT PROPOSAL DRAFT'};
const escapeHTML=value=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)}
function updateFileList(){counter.textContent=`${selectedFiles.length} ${selectedFiles.length===1?'file':'files'}`;fileHolder.innerHTML=selectedFiles.map((file,index)=>`<div class="file"><b>${escapeHTML((file.name.split('.').pop()||'FILE').slice(0,4).toUpperCase())}</b><span><strong>${escapeHTML(file.name)}</strong><small>Ready to verify</small></span><button aria-label="Remove ${escapeHTML(file.name)}" data-file-index="${index}">×</button></div>`).join('');fileHolder.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{selectedFiles.splice(Number(button.dataset.fileIndex),1);updateFileList()}))}
function addFiles(items){const available=3-selectedFiles.length;const accepted=items.slice(0,available);selectedFiles.push(...accepted);updateFileList();if(items.length>accepted.length)showToast('Tether accepts up to three proof files per audit.')}
document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{selectedDocType=button.dataset.docType;document.querySelectorAll('.tabs button').forEach(tab=>{const active=tab===button;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active))});draftLabel.textContent=docLabels[selectedDocType]}));
dz.addEventListener('click',()=>fi.click());dz.addEventListener('dragover',event=>{event.preventDefault();dz.style.borderColor='#10b981'});dz.addEventListener('dragleave',()=>dz.style.borderColor='');dz.addEventListener('drop',event=>{event.preventDefault();dz.style.borderColor='';addFiles([...event.dataTransfer.files])});fi.addEventListener('change',()=>{addFiles([...fi.files]);fi.value=''});updateFileList();
function labelFor(claim){return {green:'Evidence backed',yellow:'Needs proof',red:'Unsupported',purple:'Privacy risk'}[claim.color]||claim.action}
function hydrateAnalysis(analysis){const colors={green:'#10b981',yellow:'#f59e0b',red:'#fb7185',purple:'#a78bfa'};claims=analysis.result.claims.map(claim=>({id:claim.id,text:claim.text,verdict:labelFor(claim),kind:claim.category,confidence:Math.round(claim.confidence*100),color:colors[claim.color],evidence:claim.evidence_match,rewrite:claim.safe_rewrite,source:claim.evidence_snippets[0]?`${claim.evidence_snippets[0].file_name}${claim.evidence_snippets[0].page?` · Page ${claim.evidence_snippets[0].page}`:''}`:null}));document.querySelector('#score').textContent=analysis.result.summary.trust_score;document.querySelector('.score-copy p').textContent='Live Nemotron result';document.querySelector('.score-copy h3').textContent=`${analysis.result.summary.evidence_backed} claims are ready to publish.`;document.querySelector('.score-copy span').textContent=`${analysis.result.summary.needing_changes} claims need changes and ${analysis.result.summary.privacy_flags} privacy flag needs review.`;document.querySelector('.metrics').innerHTML=`<div><b>${analysis.result.summary.evidence_backed}</b><span>Verified</span></div><div><b>${analysis.result.summary.needing_changes}</b><span>Needs proof</span></div><div><b>${analysis.result.summary.privacy_flags}</b><span>Privacy flag</span></div>`;document.querySelector('.claim-title span').textContent=`${claims.length} reviewed`;renderClaims();selectClaim(claims[0].id)}
async function waitForAnalysis(id){for(let attempt=0;attempt<180;attempt++){const response=await fetch(`/api/analyses/${id}`);const analysis=await response.json();if(analysis.status==='complete')return analysis;if(analysis.status==='failed')throw new Error(analysis.error||'The audit could not finish');if(attempt%8===0)toast.textContent=analysis.progress?.at(-1)?.message||'Nemotron is reviewing your material…';await new Promise(resolve=>setTimeout(resolve,1000))}throw new Error('The audit is still running. Keep this tab open and try again shortly.')}
document.querySelector('#auditButton').addEventListener('click',async()=>{const btn=document.querySelector('#auditButton');if(!draft.value.trim()){showToast('Paste a draft before running an audit.');draft.focus();return}btn.innerHTML='◌ Analyzing evidence…';btn.disabled=true;try{const form=new FormData();form.append('doc_type',selectedDocType);form.append('draft_text',draft.value.trim());selectedFiles.forEach(file=>form.append('files',file));const created=await fetch('/api/analyses',{method:'POST',body:form});if(!created.ok){const detail=await created.json().catch(()=>null);throw new Error(detail?.detail?.error?.message||'Tether could not start the audit')}hydrateAnalysis(await waitForAnalysis((await created.json()).id));showToast('Live Nemotron audit complete')}catch(error){showToast(error.message)}finally{btn.innerHTML='<span>✦</span> Run Nemotron Audit';btn.disabled=false}});document.querySelector('#exportButton').addEventListener('click',()=>window.print());
