import { useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowUpRight, Check, ChevronRight, CircleHelp, ClipboardCheck, Download, FileCheck2, FileText, Flag, FolderOpen, LayoutDashboard, MoreHorizontal, Plus, Search, Settings, Sparkles, Upload, X } from "lucide-react";
import "./styles.css";

const nav = [{ label: "Workspace", icon: LayoutDashboard }, { label: "Analyses", icon: ClipboardCheck }, { label: "Evidence Packs", icon: FolderOpen }, { label: "Settings", icon: Settings }];
const claims = [
  { title: "Led a team of 12 students", status: "Verified", color: "green", confidence: "91%", source: "Advisor Letter.pdf · p. 1", excerpt: "I confirm that the student led a 12-student team during the recycling-app project.", recommendation: "Safe to publish as written." },
  { title: "Raised $3,000 for the robotics club", status: "Refine", color: "yellow", confidence: "78%", source: "Campaign Dashboard.pdf · p. 1", excerpt: "Robotics Club Spring Fundraiser. Total donations: $2,847.", recommendation: "Use: Raised nearly $2,850 for the robotics club." },
  { title: "Reduced plastic waste by 40%", status: "Needs proof", color: "red", confidence: "31%", source: "No supporting source", excerpt: "No baseline measurement or waste audit was supplied.", recommendation: "Add an audit, or remove the percentage." },
  { title: "Built an app used by 500 students", status: "Needs proof", color: "red", confidence: "42%", source: "No supporting source", excerpt: "No usage analytics or school confirmation found.", recommendation: "Use: Built an app piloted with students at my school." },
  { title: "Contact me at 555-123-4567", status: "Private", color: "purple", confidence: "95%", source: "Application draft", excerpt: "Personal contact information should not be included in public materials.", recommendation: "Remove personal contact details before sharing." },
];
const analyses = [{ name: "Recycling app proposal", type: "Project proposal", score: 72, date: "Today, 10:42 AM", status: "Complete" }, { name: "Scholarship essay", type: "Essay", score: 86, date: "Sep 18, 4:18 PM", status: "Complete" }, { name: "Research program application", type: "Application", score: 91, date: "Sep 16, 11:03 AM", status: "Complete" }];

function Button({ children, variant = "default", icon: Icon, ...props }) { return <button className={`button ${variant}`} {...props}>{Icon && <Icon size={15}/>} {children}</button>; }
function Badge({ children, color = "neutral" }) { return <span className={`badge ${color}`}>{children}</span>; }
function Score({ value }) { return <div className="score"><strong>{value}</strong><span>/100</span></div>; }

function Sidebar({ page, setPage }) { return <aside className="sidebar"><div className="brand"><img className="brand-logo" src="/tether-bird-logo.png" alt="Tether logo"/><span>Tether</span></div><nav>{nav.map(({label, icon: Icon}) => <button key={label} onClick={() => setPage(label)} className={`nav-item ${page === label ? "active" : ""}`}><Icon size={16}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><CircleHelp size={16}/><span>Help center</span></button><div className="user"><span className="avatar">AS</span><span><b>Anuroop Saini</b><small>Student workspace</small></span><MoreHorizontal size={16}/></div></div></aside> }
function Topbar({ title, action }) { return <header className="topbar"><div><span className="eyebrow">TETHER / {title.toUpperCase()}</span><h1>{title}</h1></div>{action}</header> }
function Stat({ label, value, note }) { return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }

function Workspace({ openAnalysis }) { return <main className="content"><Topbar title="Workspace" action={<Button icon={Plus}>New analysis</Button>}/><div className="workspace-grid"><section><div className="section-heading"><div><h2>Good morning, Anuroop</h2><p>Keep your strongest work supported and ready to share.</p></div><Button variant="secondary" icon={Upload}>Upload draft</Button></div><div className="stats-grid"><Stat label="Average trust score" value="83" note="Across 3 completed analyses"/><Stat label="Claims verified" value="18" note="6 need your attention"/><Stat label="Evidence files" value="12" note="Across your workspace"/></div><div className="panel"><div className="panel-head"><div><h2>Recent analyses</h2><p>Your latest drafts and evidence reviews.</p></div><Button variant="ghost">View all <ArrowUpRight size={14}/></Button></div><div className="table"><div className="tr th"><span>Analysis</span><span>Trust score</span><span>Status</span><span>Updated</span><span></span></div>{analyses.map((a, i) => <button className="tr" key={a.name} onClick={openAnalysis}><span className="file-cell"><span className="file-icon"><FileText size={16}/></span><span><b>{a.name}</b><small>{a.type}</small></span></span><Score value={a.score}/><span><Badge color="green">{a.status}</Badge></span><span className="muted">{a.date}</span><ChevronRight size={16}/></button>)}</div></div></section><aside className="side-column"><div className="panel compact"><div className="panel-head"><div><h2>Getting started</h2><p>Three steps to a stronger submission.</p></div></div>{[["01","Add your draft"],["02","Attach your proof"],["03","Review decisions"]].map(([n,t],i)=><div className="step" key={t}><span>{n}</span><div><b>{t}</b><small>{i===0?"Essays, resumes, proposals, and more.":i===1?"Letters, receipts, screenshots, or notes.":"Accept safer wording and export."}</small></div>{i===0?<Check size={16}/>:null}</div>)}</div><div className="panel compact callout"><Sparkles size={17}/><h3>Evidence Packs</h3><p>Create a clear reviewer-facing record of the claims you can stand behind.</p><button onClick={openAnalysis}>See an example <ArrowUpRight size={14}/></button></div></aside></div></main> }

function Analysis({ setPage }) { const [selected, setSelected] = useState(0); const claim = claims[selected]; return <main className="analysis-main"><Topbar title="Recycling app proposal" action={<div className="action-row"><Button variant="secondary" icon={Download}>Export pack</Button><Button icon={Plus}>New analysis</Button></div>}/><div className="analysis-layout"><section className="claims-pane"><div className="analysis-summary"><div><span className="eyebrow">PROJECT PROPOSAL · COMPLETE</span><h2>Evidence review</h2><p>5 claims reviewed against 2 supporting files.</p></div><Score value="72"/></div><div className="filter-row"><button className="filter active">All <span>5</span></button><button className="filter">Verified <span>1</span></button><button className="filter">Attention <span>4</span></button><div className="search"><Search size={15}/><input placeholder="Filter claims"/></div></div><div className="claim-list">{claims.map((item,index)=><button key={item.title} onClick={()=>setSelected(index)} className={`claim-row ${selected === index ? "selected" : ""}`}><span className={`status-dot ${item.color}`}></span><span className="claim-copy"><b>{item.title}</b><small>{item.recommendation}</small></span><span className="claim-meta"><Badge color={item.color}>{item.status}</Badge><small>{item.confidence}</small></span><ChevronRight size={16}/></button>)}</div></section><Inspector claim={claim}/></div></main> }

function Inspector({ claim }) { return <aside className="inspector"><div className="inspector-head"><span>CLAIM INSPECTOR</span><button aria-label="Close inspector"><X size={16}/></button></div><div className="inspector-body"><Badge color={claim.color}>{claim.status}</Badge><h2>{claim.title}</h2><div className="confidence"><span>Confidence</span><b>{claim.confidence}</b><div><i style={{width: claim.confidence}}/></div></div><div className="inspector-section"><span className="label">DECISION</span><p>{claim.recommendation}</p></div><div className="inspector-section"><span className="label">EVIDENCE MATCH</span><div className="evidence"><div><FileCheck2 size={16}/><span>{claim.source}</span></div><blockquote>“{claim.excerpt}”</blockquote></div></div><div className="inspector-section"><span className="label">PROVENANCE</span><p className="muted">Evidence supplied by the student and matched to this claim.</p></div></div><div className="inspector-actions"><Button variant="secondary">View source</Button><Button>Accept rewrite</Button></div></aside> }

function Analyses({ openAnalysis }) { return <main className="content"><Topbar title="Analyses" action={<Button icon={Plus}>New analysis</Button>}/><div className="toolbar"><div className="search wide"><Search size={15}/><input placeholder="Search analyses"/></div><Button variant="secondary">All types <ChevronRight size={14}/></Button></div><div className="panel"><div className="table"><div className="tr th"><span>Analysis</span><span>Trust score</span><span>Status</span><span>Updated</span><span></span></div>{[...analyses, { name:"Club grant proposal", type:"Proposal", score:64,date:"Sep 10, 2:26 PM",status:"Complete" },{name:"Student council résumé",type:"Resume",score:78,date:"Sep 04, 9:30 AM",status:"Complete"}].map(a=><button className="tr" key={a.name} onClick={openAnalysis}><span className="file-cell"><span className="file-icon"><FileText size={16}/></span><span><b>{a.name}</b><small>{a.type}</small></span></span><Score value={a.score}/><span><Badge color={a.score<70?"yellow":"green"}>{a.status}</Badge></span><span className="muted">{a.date}</span><ChevronRight size={16}/></button>)}</div></div></main> }
function Packs() { return <main className="content"><Topbar title="Evidence Packs" action={<Button icon={Plus}>Create pack</Button>}/><div className="section-heading"><div><h2>Share work with confidence</h2><p>Evidence Packs pair your strongest claims with clear, reviewer-ready provenance.</p></div></div><div className="packs-grid">{analyses.map((a,i)=><article className="pack-card" key={a.name}><div className="pack-preview"><div className="preview-line strong"/><div className="preview-line"/><div className="preview-block"/><div className="preview-line"/><div className="preview-block"/></div><div><Badge color="green">Ready</Badge><h3>{a.name}</h3><p>{i+1} verified claim{i?"s":""} · Last updated {a.date}</p><button>Open pack <ArrowUpRight size={14}/></button></div></article>)}</div></main> }
function SettingsPage() { return <main className="content"><Topbar title="Settings"/><div className="settings"><section className="panel"><div className="panel-head"><div><h2>Workspace preferences</h2><p>Control how Tether handles your analysis data.</p></div></div><label>Workspace name<input value="Anuroop's workspace" readOnly/></label><label>Default document type<select defaultValue="Essay"><option>Essay</option><option>Resume</option><option>Project proposal</option></select></label><div className="toggle-row"><div><b>Keep analysis history</b><small>Save drafts and evidence for future review.</small></div><span className="toggle on"><i/></span></div><Button>Save changes</Button></section><section className="panel compact"><h2>API connection</h2><p>Tether connects to the configured analysis API.</p><div className="api-row"><span className="status-dot green"/> <code>http://localhost:8000/api</code><Badge color="green">Connected</Badge></div></section></div></main> }
function App(){ const [page,setPage]=useState("Workspace"); const openAnalysis=()=>setPage("Review"); const screen=page==="Workspace"?<Workspace openAnalysis={openAnalysis}/>:page==="Review"?<Analysis setPage={setPage}/>:page==="Analyses"?<Analyses openAnalysis={openAnalysis}/>:page==="Evidence Packs"?<Packs/>:<SettingsPage/>; return <div className="app"><Sidebar page={page} setPage={setPage}/>{screen}</div> }
createRoot(document.getElementById("root")).render(<App/>);
