import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowUpRight, Check, ChevronRight, CircleHelp, ClipboardCheck, Download, FileCheck2, FileText, FolderOpen, LayoutDashboard, MoreHorizontal, Plus, Search, Settings, Sparkles, Upload, X } from "lucide-react";
import "./styles.css";

const nav = [{ label: "Workspace", icon: LayoutDashboard }, { label: "Analyses", icon: ClipboardCheck }, { label: "Evidence Packs", icon: FolderOpen }, { label: "Settings", icon: Settings }];
const labels = { publish: "Verified", soften: "Refine", needs_evidence: "Needs proof", remove_sensitive_data: "Private" };
const recommendation = claim => claim.accepted_rewrite || claim.safe_rewrite || claim.action;
const errorMessage = body => body?.error?.message || "Tether could not complete that request.";

function Button({ children, variant = "default", icon: Icon, ...props }) { return <button className={`button ${variant}`} {...props}>{Icon && <Icon size={15}/>} {children}</button>; }
function Badge({ children, color = "neutral" }) { return <span className={`badge ${color}`}>{children}</span>; }
function Score({ value }) { return <div className="score"><strong>{value}</strong><span>/100</span></div>; }
function Topbar({ title, action }) { return <header className="topbar"><div><span className="eyebrow">TETHER / {title.toUpperCase()}</span><h1>{title}</h1></div>{action}</header>; }
function Stat({ label, value, note }) { return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }

function Sidebar({ page, setPage }) { return <aside className="sidebar"><div className="brand"><img className="brand-logo" src="/tether-bird-logo.png" alt="Tether logo"/><span>Tether</span></div><nav>{nav.map(({label, icon: Icon}) => <button key={label} onClick={() => setPage(label)} className={`nav-item ${page === label ? "active" : ""}`}><Icon size={16}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><CircleHelp size={16}/><span>Help center</span></button><div className="user"><span className="avatar">AS</span><span><b>Anuroop Saini</b><small>Student workspace</small></span><MoreHorizontal size={16}/></div></div></aside>; }

function Workspace({ analysis, startNew, runDemo, openAnalysis }) {
  const summary = analysis?.result?.summary;
  return <main className="content"><Topbar title="Workspace" action={<Button icon={Plus} onClick={startNew}>New analysis</Button>}/><div className="workspace-grid"><section><div className="section-heading"><div><h2>Good morning, Anuroop</h2><p>Keep your strongest work supported and ready to share.</p></div><Button variant="secondary" icon={Upload} onClick={startNew}>Upload draft</Button></div><div className="stats-grid"><Stat label="Trust score" value={summary?.trust_score ?? "—"} note={summary ? "Latest completed analysis" : "Run an analysis to begin"}/><Stat label="Claims verified" value={summary?.evidence_backed ?? "—"} note={summary ? `${summary.needing_changes} need attention` : "Evidence-backed claims"}/><Stat label="Evidence files" value={analysis?.evidence?.length ?? "—"} note={analysis ? "In the current analysis" : "Attach up to three proof files"}/></div><div className="panel"><div className="panel-head"><div><h2>Recent analyses</h2><p>{analysis ? "Your latest completed review." : "Start with a draft or the guided demo."}</p></div>{analysis ? <Button variant="ghost" onClick={openAnalysis}>Open review <ArrowUpRight size={14}/></Button> : <Button variant="ghost" onClick={runDemo}>Run demo <ArrowUpRight size={14}/></Button>}</div>{analysis ? <div className="table"><div className="tr th"><span>Analysis</span><span>Trust score</span><span>Status</span><span>Updated</span><span></span></div><button className="tr" onClick={openAnalysis}><span className="file-cell"><span className="file-icon"><FileText size={16}/></span><span><b>{analysis.doc_type.replaceAll("_", " ")}</b><small>{analysis.result.claims.length} claims reviewed</small></span></span><Score value={analysis.result.summary.trust_score}/><span><Badge color="green">Complete</Badge></span><span className="muted">Just now</span><ChevronRight size={16}/></button></div> : <div className="empty-state"><FileText size={18}/><p>No analyses yet. Upload a draft or explore the demo.</p></div>}</div></section><aside className="side-column"><div className="panel compact"><div className="panel-head"><div><h2>Getting started</h2><p>Three steps to a stronger submission.</p></div></div>{[["01","Add your draft"],["02","Attach your proof"],["03","Review decisions"]].map(([n,t])=><div className="step" key={t}><span>{n}</span><div><b>{t}</b><small>{t === "Add your draft" ? "Essays, resumes, proposals, and more." : t === "Attach your proof" ? "Letters, receipts, screenshots, or notes." : "Accept safer wording and export."}</small></div>{t === "Add your draft" ? <Check size={16}/> : null}</div>)}</div><div className="panel compact callout"><Sparkles size={17}/><h3>Evidence Packs</h3><p>Create a reviewer-facing record of the claims you can stand behind.</p><button onClick={analysis ? openAnalysis : runDemo}>{analysis ? "Review your pack" : "See the demo"} <ArrowUpRight size={14}/></button></div></aside></div></main>;
}

function CreateAnalysis({ onSubmit, busy, message }) {
  const [docType, setDocType] = useState("essay");
  const [draft, setDraft] = useState("");
  const [files, setFiles] = useState([]);
  const submit = event => { event.preventDefault(); onSubmit({ docType, draft, files }); };
  return <main className="content"><Topbar title="New analysis"/><form className="create-grid" onSubmit={submit}><section className="panel create-panel"><div className="panel-head"><div><h2>Draft & evidence</h2><p>Only attach sources you are comfortable sharing for this review.</p></div></div><label>Document type<select value={docType} onChange={event => setDocType(event.target.value)}><option value="essay">Essay</option><option value="resume">Resume</option><option value="project_proposal">Project proposal</option><option value="application">Application</option></select></label><label>Draft<textarea className="draft-input" value={draft} onChange={event => setDraft(event.target.value)} placeholder="Paste your essay, résumé, application, or proposal."/></label><label>Supporting evidence <input type="file" multiple onChange={event => setFiles([...event.target.files].slice(0, 3))}/><small>{files.length ? `${files.length} file${files.length === 1 ? "" : "s"} selected` : "Up to three files, 10 MB each."}</small></label>{message ? <p className="form-message">{message}</p> : null}<div className="form-actions"><Button variant="secondary" type="button" onClick={() => setDraft("")}>Clear</Button><Button icon={Sparkles} type="submit" disabled={busy || !draft.trim()}>{busy ? "Analyzing…" : "Run Nemotron audit"}</Button></div></section><aside className="panel compact form-aside"><span className="label">WHAT TETHER CHECKS</span><div className="step"><span>01</span><div><b>Exact support</b><small>Claims are matched to supplied evidence.</small></div></div><div className="step"><span>02</span><div><b>Privacy risk</b><small>Personal data is flagged before sharing.</small></div></div><div className="step"><span>03</span><div><b>Safe wording</b><small>Receive a concrete, credible rewrite.</small></div></div></aside></form></main>;
}

function Analysis({ analysis, acceptRewrite, exportPack, startNew }) {
  const [selected, setSelected] = useState(0);
  const items = analysis.result.claims;
  const claim = items[selected] || items[0];
  useEffect(() => setSelected(0), [analysis.id]);
  return <main className="analysis-main"><Topbar title={analysis.doc_type.replaceAll("_", " ")} action={<div className="action-row"><Button variant="secondary" icon={Download} onClick={exportPack}>Export pack</Button><Button icon={Plus} onClick={startNew}>New analysis</Button></div>}/><div className="analysis-layout"><section className="claims-pane"><div className="analysis-summary"><div><span className="eyebrow">{analysis.doc_type.replaceAll("_", " ").toUpperCase()} · COMPLETE</span><h2>Evidence review</h2><p>{items.length} claims reviewed against {analysis.evidence.length} supporting files.</p></div><Score value={analysis.result.summary.trust_score}/></div><div className="filter-row"><button className="filter active">All <span>{items.length}</span></button><button className="filter">Verified <span>{analysis.result.summary.evidence_backed}</span></button><button className="filter">Attention <span>{analysis.result.summary.needing_changes + analysis.result.summary.privacy_flags}</span></button><div className="search"><Search size={15}/><input placeholder="Filter claims"/></div></div><div className="claim-list">{items.map((item,index)=><button key={item.id} onClick={() => setSelected(index)} className={`claim-row ${selected === index ? "selected" : ""}`}><span className={`status-dot ${item.color}`}/><span className="claim-copy"><b>{item.text}</b><small>{recommendation(item)}</small></span><span className="claim-meta"><Badge color={item.color}>{labels[item.verdict] || item.action}</Badge><small>{Math.round(item.confidence * 100)}%</small></span><ChevronRight size={16}/></button>)}</div></section><Inspector analysisId={analysis.id} claim={claim} acceptRewrite={acceptRewrite}/></div></main>;
}

function Inspector({ analysisId, claim, acceptRewrite }) {
  const snippet = claim.evidence_snippets[0];
  return <aside className="inspector"><div className="inspector-head"><span>CLAIM INSPECTOR</span><button aria-label="Close inspector"><X size={16}/></button></div><div className="inspector-body"><Badge color={claim.color}>{labels[claim.verdict] || claim.action}</Badge><h2>{claim.text}</h2><div className="confidence"><span>Confidence</span><b>{Math.round(claim.confidence * 100)}%</b><div><i style={{width: `${Math.round(claim.confidence * 100)}%`}}/></div></div><div className="inspector-section"><span className="label">DECISION</span><p>{recommendation(claim)}</p></div><div className="inspector-section"><span className="label">EVIDENCE MATCH</span><div className="evidence"><div><FileCheck2 size={16}/><span>{snippet ? `${snippet.file_name}${snippet.page ? ` · p. ${snippet.page}` : ""}` : "No supporting source"}</span></div><blockquote>“{snippet?.text || claim.evidence_match}”</blockquote></div></div><div className="inspector-section"><span className="label">PROVENANCE</span><p className="muted">{claim.provenance_note || "Evidence supplied by the student and matched to this claim."}</p></div></div><div className="inspector-actions"><Button variant="secondary" disabled={!snippet} onClick={() => window.open(`/api/analyses/${analysisId}/evidence-pack/preview`, "_blank", "noopener,noreferrer")}>View source</Button><Button disabled={!claim.safe_rewrite || claim.accepted_rewrite} onClick={() => acceptRewrite(claim.id)}>{claim.accepted_rewrite ? "Rewrite accepted" : "Accept rewrite"}</Button></div></aside>;
}

function Analyses({ analysis, openAnalysis, startNew }) { return <main className="content"><Topbar title="Analyses" action={<Button icon={Plus} onClick={startNew}>New analysis</Button>}/><div className="toolbar"><div className="search wide"><Search size={15}/><input placeholder="Search analyses"/></div></div><div className="panel">{analysis ? <div className="table"><div className="tr th"><span>Analysis</span><span>Trust score</span><span>Status</span><span>Updated</span><span></span></div><button className="tr" onClick={openAnalysis}><span className="file-cell"><span className="file-icon"><FileText size={16}/></span><span><b>{analysis.doc_type.replaceAll("_", " ")}</b><small>{analysis.result.claims.length} claims reviewed</small></span></span><Score value={analysis.result.summary.trust_score}/><span><Badge color="green">Complete</Badge></span><span className="muted">Just now</span><ChevronRight size={16}/></button></div> : <div className="empty-state"><p>Analyses you run will appear here.</p><Button onClick={startNew}>Create analysis</Button></div>}</div></main>; }

function Packs({ analysis, openAnalysis }) { const verified = analysis?.result?.summary.evidence_backed ?? 0; return <main className="content"><Topbar title="Evidence Packs" action={<Button icon={Plus} onClick={openAnalysis} disabled={!analysis}>Create pack</Button>}/><div className="section-heading"><div><h2>Share work with confidence</h2><p>Evidence Packs pair your strongest claims with clear, reviewer-ready provenance.</p></div></div>{analysis ? <div className="packs-grid"><article className="pack-card"><div className="pack-preview"><div className="preview-line strong"/><div className="preview-line"/><div className="preview-block"/><div className="preview-line"/><div className="preview-block"/></div><div><Badge color="green">Ready</Badge><h3>{analysis.doc_type.replaceAll("_", " ")}</h3><p>{verified} verified claim{verified === 1 ? "" : "s"} · Current analysis</p><button onClick={openAnalysis}>Open pack <ArrowUpRight size={14}/></button></div></article></div> : <div className="panel empty-state"><p>Complete an analysis to create an Evidence Pack.</p></div>}</main>; }

function SettingsPage({ health }) { return <main className="content"><Topbar title="Settings"/><div className="settings"><section className="panel"><div className="panel-head"><div><h2>Workspace preferences</h2><p>Control how Tether handles your analysis data.</p></div></div><label>Workspace name<input value="Anuroop's workspace" readOnly/></label><label>Default document type<select defaultValue="Essay"><option>Essay</option><option>Resume</option><option>Project proposal</option></select></label><div className="toggle-row"><div><b>Keep analysis history</b><small>Save drafts and evidence for future review.</small></div><span className="toggle on"><i/></span></div><Button>Save changes</Button></section><section className="panel compact"><h2>API connection</h2><p>{health ? `${health.nemotron} · ${health.model}` : "Checking the configured analysis API."}</p><div className="api-row"><span className="status-dot green"/> <code>/api</code><Badge color="green">{health ? "Connected" : "Checking"}</Badge></div></section></div></main>; }

function App() {
  const [page, setPage] = useState("Workspace");
  const [analysis, setAnalysis] = useState(null);
  const [health, setHealth] = useState(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/health").then(response => response.ok ? response.json() : null).then(setHealth).catch(() => setHealth(null)); }, []);
  const poll = async id => { for (let attempt = 0; attempt < 90; attempt += 1) { const response = await fetch(`/api/analyses/${id}`); const body = await response.json(); if (!response.ok) throw new Error(errorMessage(body)); if (body.status === "complete") return body; if (body.status === "failed") throw new Error(body.error || "The analysis could not finish."); await new Promise(resolve => setTimeout(resolve, 500)); } throw new Error("The analysis is taking longer than expected. Please try again."); };
  const startNew = () => { setMessage(""); setPage("New analysis"); };
  const begin = async request => { if (!request.draft.trim()) return; setBusy(true); setMessage("Nemotron is reviewing your claims…"); try { const form = new FormData(); form.append("doc_type", request.docType); form.append("draft_text", request.draft.trim()); request.files.forEach(file => form.append("files", file)); const response = await fetch("/api/analyses", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(errorMessage(body)); setAnalysis(await poll(body.id)); setPage("Review"); setMessage(""); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const runDemo = async () => { setBusy(true); setMessage("Loading the guided demo…"); try { const response = await fetch("/api/demo", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(errorMessage(body)); setAnalysis(await poll(body.id)); setPage("Review"); setMessage(""); } catch (error) { setMessage(error.message); setPage("New analysis"); } finally { setBusy(false); } };
  const acceptRewrite = async claimId => { if (!analysis) return; const response = await fetch(`/api/analyses/${analysis.id}/claims/${claimId}/accept-rewrite`, { method: "POST" }); const body = await response.json(); if (!response.ok) { setMessage(errorMessage(body)); return; } setAnalysis(current => ({ ...current, result: { ...current.result, claims: current.result.claims.map(claim => claim.id === body.id ? body : claim) } })); };
  const exportPack = () => analysis && window.open(`/api/analyses/${analysis.id}/evidence-pack`, "_blank", "noopener,noreferrer");
  const openAnalysis = () => analysis ? setPage("Review") : runDemo();
  const screen = page === "Workspace" ? <Workspace analysis={analysis} startNew={startNew} runDemo={runDemo} openAnalysis={openAnalysis}/> : page === "New analysis" ? <CreateAnalysis onSubmit={begin} busy={busy} message={message}/> : page === "Review" && analysis ? <Analysis analysis={analysis} acceptRewrite={acceptRewrite} exportPack={exportPack} startNew={startNew}/> : page === "Analyses" ? <Analyses analysis={analysis} openAnalysis={openAnalysis} startNew={startNew}/> : page === "Evidence Packs" ? <Packs analysis={analysis} openAnalysis={openAnalysis}/> : <SettingsPage health={health}/>;
  return <div className="app"><Sidebar page={page === "New analysis" || page === "Review" ? "Workspace" : page} setPage={setPage}/>{screen}</div>;
}
createRoot(document.getElementById("root")).render(<App/>);
